### ISSUE TITLE
Exam review question number styling

### ISSUE THREAD

**Issue by tomasflopes** [Nucleo-Estudantes-Informatica-ISEP/antirecurso#45]
Let's be honest, the current styling for question numbering in the website is not great. The usage of red and orange colors for the numbering makes it difficult to distinguish between the two, especially in certain brightness settings where the difference becomes barely noticeable. To enhance the user experience and improve the visual appeal of the website, it is necessary to rethink the way this information is displayed.

![image](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/50304854/e9aba569-429d-4828-a24d-7f8243391ee3)

By reevaluating the styling approach for question numbering, we can find a better solution that ensures clarity and ease of differentiation. It is important to select colors that have a sufficient contrast and are distinguishable across various display settings. This will enhance the overall beauty of the website while also improving the usability and user experience for visitors.

Additionally, it would be beneficial to display the score of the exam on the review page, emphasizing the result of the taken exam. This provides users with immediate visibility of their performance and adds much needed information in the review process.

Hint: When revising the styling for question numbering, ensure that the difference between wrong and correct answers is noticeable at first glance.

**Comment by pintohen** [comment]
Hey, I had an idea, however you might not find it the most appealing one. As we can see the challenging part of this is that we can't really change some colors since it goes along with the rest of the website, so we are limited to changing the wrong answer one. I could easily find a color that fits almost all your requirements, is distinguishable from right ones, does not confuse with the selected one and is aesthetically appealing, however it doesn't really vibrate mentally the sensation that the question is wrong, contrary to the red color, an alarming one.

So instead of changing the background color, i changed the text color to black, so it contrasts with all of the other options, looks somewhat fine and you can notice it is wrong, visually.

<img width="770" alt="Screenshot 2023-06-28 at 08 12 59" src="https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/97101738/f4d6c421-6283-48ec-b849-ce2498a24504">

Here it is, let me know what you think, I already read some code and can deliver it quickly.

**Comment by Eduardoooxd** [comment]
Imo this approach seems like a quick win and I can approve it. 

But still, we have a major problem with the accessibility of the whole website (in a lot of sections, the contrast between the text and the background color is not enough, for example background color of orange with white on middle), the color in the stats graphs is weird as well imo.

Now that the exam phase is almost ending, the number of users is decreasing, so we have a lot of time to tweak and try different things. So any suggestion is really helpful !

**Comment by pintohen** [comment]
I will create a branch to commit related to this issue then, if any idea comes meanwhile i can implement it no issue.

Related to the stats graph i will look into that and see what comes to mind.

Anything needed contact me via GitHub/any social on my profile :)

**Comment by pintohen** [comment]
Also, is this the graph you're talking about?
<img width="1251" alt="image" src="https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/97101738/e1dcc51d-a827-4587-9470-e807407437d8">

**Comment by tomasflopes** [comment]
The animations in the documentation examples do indeed look better, and the complexity level doesn't appear to increase significantly. Also, for what I've seen the library doesn't remove any features we already have with Chart.js (such as hiding certain chart components, hover and reveal animation).

Considering this, I believe an almost direct port would be easy to implement and could be highly beneficial for the project.

**Comment by Eduardoooxd** [comment]
I created an [PR to add dark mode](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/pull/51) to AntiRecurso, and this of course impacts the aesthetic and colors of the graph. 

![image](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/40842048/bd90b64b-bbb5-443c-9cf0-5293b772bfb6)

![image](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/40842048/2e0453dd-e8e5-4a20-a6b2-201111789be2)

We should also take dark mode in account from now on.
